#!/usr/bin/env bash
set -eu

HERE=$(dirname $0)
. $HERE/common

docker exec $DB_CONTAINER psql -U vimc -d montagu -f clear_schema.sql
echo "Creating montagu schema"
docker run --rm --network=$DB_NETWORK $DB_MIGRATE_IMAGE
