#!/usr/bin/env bash
set -eu

HERE=$(dirname $0)
. $HERE/common


docker network create $DB_NETWORK

echo "Starting container"
docker run --rm -p 5432:5432 --network=$DB_NETWORK -d --name $DB_CONTAINER $DB_IMAGE

# Wait for things to become responsive
docker exec $DB_CONTAINER montagu-wait.sh

# Do the migrations
echo "Creating montagu schema"
docker run --rm --network=$DB_NETWORK $DB_MIGRATE_IMAGE

echo "Setting up utility scripts"
cat <<EOF > clear_schema.sql
DROP SCHEMA public cascade;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO vimc;
GRANT ALL ON SCHEMA public TO postgres;
EOF

docker cp clear_schema.sql $DB_CONTAINER:/

rm -f clear_schema.sql
