# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

services:
  - docker

before_install
- docker pull docker.montagu.dide.ic.ac.uk:5000/montagu-db:master


sudo: false
cache: packages
r_packages: covr
after_success:
  - Rscript -e 'covr::codecov()'