# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

services:
  - docker

before_install:
- docker pull vimc/montagu-db:master

sudo: false
cache: packages
r_packages: covr
after_success:
  - Rscript -e 'covr::codecov()'