#' Transform touchstone-relevant extracted data into tables ready for
#' database import. This should be called from the transform code of montagu-import,
#' calling `stoner::transform(extracted_data)` with the same argument provided
#' to the montagu-import transform function.
#'
#' For specific information on what steps the transform function does.
#' see the vignette.
#' @title Transform extracted_data into transformed_data
#' @export
#' @param extracted_data The extracted data that was generated by the previous extract call
#' @return A list of data frames, one for each table, with names matching the
#'   database table names, and containing rows to be added to that table.

transform <- function(extracted_data) {
  t <- c(transform_touchstone(extracted_data))

  # Remove all rows that shouldn't be added/edited. (ie, database
  # already contains identical rows).

  for (table in c('touchstone', 'touchstone_name')) {
    if (table %in% names(t)) {
      t[[table]] <- t[[table]][t[[table]]$add_to_database, ]
      t[[table]]$add_to_database <- NULL
    }
  }
}
